package book.mapper;

import book.model.UserRoleMid;
import book.model.UserRoleMidExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleMidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_mid
     *
     * @mbg.generated Sun May 14 16:36:04 CST 2017
     */
    long countByExample(UserRoleMidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_mid
     *
     * @mbg.generated Sun May 14 16:36:04 CST 2017
     */
    int deleteByExample(UserRoleMidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_mid
     *
     * @mbg.generated Sun May 14 16:36:04 CST 2017
     */
    int insert(UserRoleMid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_mid
     *
     * @mbg.generated Sun May 14 16:36:04 CST 2017
     */
    int insertSelective(UserRoleMid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_mid
     *
     * @mbg.generated Sun May 14 16:36:04 CST 2017
     */
    List<UserRoleMid> selectByExample(UserRoleMidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_mid
     *
     * @mbg.generated Sun May 14 16:36:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserRoleMid record, @Param("example") UserRoleMidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role_mid
     *
     * @mbg.generated Sun May 14 16:36:04 CST 2017
     */
    int updateByExample(@Param("record") UserRoleMid record, @Param("example") UserRoleMidExample example);
}