package book.model;

public class UserRoleMid {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role_mid.user_id
     *
     * @mbg.generated Sun May 14 16:36:04 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role_mid.role_id
     *
     * @mbg.generated Sun May 14 16:36:04 CST 2017
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role_mid.user_id
     *
     * @return the value of sys_user_role_mid.user_id
     *
     * @mbg.generated Sun May 14 16:36:04 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role_mid.user_id
     *
     * @param userId the value for sys_user_role_mid.user_id
     *
     * @mbg.generated Sun May 14 16:36:04 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role_mid.role_id
     *
     * @return the value of sys_user_role_mid.role_id
     *
     * @mbg.generated Sun May 14 16:36:04 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role_mid.role_id
     *
     * @param roleId the value for sys_user_role_mid.role_id
     *
     * @mbg.generated Sun May 14 16:36:04 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}